# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Count_in_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countWords', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Indexer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='count_in_file',
            name='indexer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Indexer'),
        ),
    ]
