# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='count_in_file',
            name='link',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='count_in_file',
            name='countWords',
            field=models.IntegerField(),
        ),
    ]
