# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20160609_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='count_in_file',
            name='link',
        ),
        migrations.AddField(
            model_name='count_in_file',
            name='link_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
