# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20160609_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='count_in_file',
            name='link_id',
        ),
        migrations.AddField(
            model_name='count_in_file',
            name='link',
            field=models.CharField(default='', max_length=300),
        ),
    ]
